# Generated by Django 5.2.9 on 2026-03-29 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('college', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='students/')),
                ('id_proof', models.FileField(upload_to='idproof/')),
                ('joining_date', models.DateField()),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room')),
            ],
        ),
    ]
