# Generated by Django 5.2.9 on 2026-03-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_password_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='joining_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
