# Generated by Django 5.2.9 on 2026-03-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
                ('total_beds', models.IntegerField()),
                ('available_beds', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('room_image', models.ImageField(upload_to='rooms/')),
            ],
        ),
    ]
